### PR TITLE
upgrade nan to support node v0.11.10

### PR DESCRIPTION
**Pull request by ktmud**

### CODE REVIEW

**Comment by kodeninja** [comment]
Hey @rvagg! Any idea when `lmdb` will start building on `node 0.12`?

**Comment by rvagg** [comment]
Someone else is going to have to take over this work if they are using this module, I don't use it actively and can't justify spending any time on this.

One word of caution though. NAN version 2 is about to land and it's a world of pain so I would advise holding off until NAN 2 ships properly and has documentation and then it'll be more _forward compatible_ with io.js and a future major Node.js release.

**Comment by kodeninja** [comment]
I see. Thanks for the heads up! We actually rely on {{level-lmdb}}, so _both_ these will have to be updated before we can move to node 0.12.

**Comment by chjj** [comment]
Resolved with the latest rewrite. Closing.

**Pull request closed without merging**
